### ISSUE TITLE
Images do not have height in Firefox

### ISSUE THREAD

**Issue by webcraftsman** [laurenhallden/travellog#1]
I was viewing your site in Firefox 57.0 and noticed the images do not have height.  Looks like FF is handling your padding declarations in Grid differently than in Chrome.
![screen shot 2017-11-28 at 10 01 43 am](https://user-images.githubusercontent.com/781439/33326542-430f0ca2-d423-11e7-9057-d9d640824c3b.png)

**Comment by laurenhallden** [comment]
@webcraftsman ahhh, good catch! I'll take a look tonight.
